/**
 * Created By xun  on 2018-12-26 21:53.
 * Description: user
 */
export const STORAGE_KEY_MAPPING = {
  AUTH_TOKEN: 'AUTH_TOKEN',
  API_COUNT: 'API_COUNT',
  AVATAR: 'AVATAR',
  ROLES: 'ROLES',
  LOGIN_ACCOUNT: 'LOGIN_ACCOUNT',
  USER_NAME: 'USER_NAME',
  USER_ID: 'USER_ID',
  REMEMBER_ACCOUNTS: 'REMEMBER_ACCOUNTS',
  PERMISSION_LIST: 'PERMISSION_LIST',
  ENT_CERT_PROGRESS: 'ENT_CERT_PROGRESS',
  FAVICON_ICO: 'FAVICON_ICO',
  NAV_LOGO: 'NAV_LOGO',
  LOGIN_LOGO: 'LOGIN_LOGO',
  SYS_NAME: 'SYS_NAME'
};
